### ISSUE TITLE
Incorrect Namespace Reference

### ISSUE THREAD

**Issue by wondersavant** [btholt/complete-intro-to-containers-v2#4]
Crafting Containers by Hand  
Namespaces

> "Enter namespaces. Namespaces allow you to hide processes from other processes. If we give each chroot'd environment different sets of namespaces, now Alice, Bob, and Eve can't see each others' processes (they even get different process PIDs, or process IDs, so they can't guess what the others have) and you can't steal or hijack what you can't see!
> 
> There's a lot more depth to namespaces beyond what I've outlined here. The above is describing just the UTS (or UNIX Timesharing) namespace. There are more namespaces as well and this will help these containers stay isloated from each other."

The documentation incorrectly refers to the UTS (UNIX Timesharing) namespace when it should be referring to the PID namespace. Specifically, the text states: 

> "The above is describing just the UTS (or UNIX Timesharing) namespace," 

but it is actually describing the PID namespace.

**Comment by dtauer** [comment]
@wondersavant Thank you for all your help catching the errors in the documentation! We'll be releasing the edited, full-featured course this week so I'm working through these updates and will have the site patched today.

I won't blow up your inbox with messages for each issue unless I need clarification. Thanks again for your help!

**Comment by wondersavant** [comment]
I am glad I could help. I wanted to let you know that I didn't submit issues for the typos and grammar corrections because I am not a native English speaker and there were quite a few. I plan to review the course again once I finish it and will submit those issues then. In the meantime, you might consider using tools like Grammarly or ChatGPT for those corrections.

Thank you! :)
